apiVersion: v1
kind: Service
metadata:
  name: skala-stock-api
  namespace: skala-edu
spec:
  selector:
    app: skala-stock-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: mgmt
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP


